name: LADY KIWI
favicon: null
layout_spectrum: 1
typography_spectrum: 0.4042553
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f7f4ed'
    - '#e28f63'
    - '#c9784d'
    - '#e7c095'
    - '#a85935'
  brandStrength: 1
  lightness: 0.3851064
  saturation: 1
  rhythmicContrast: 0
purpose: []
