name: LADY KIWI
favicon: null
layout_spectrum: 1
typography_spectrum: 0.54752
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#b8d4ae'
    - '#73ab62'
    - '#00100d'
    - '#2a4124'
  brandStrength: 0.5
  lightness: 0.05039323284290731
  saturation: 0.875
  rhythmicContrast: 0.9163537812419236
purpose: []
