typography_spectrum: 0.40185
color:
  brandColors:
    - '#ffffff'
    - '#ff2d40'
    - '#413630'
    - '#d3d1a1'
    - '#996f68'
  brandStrength: 0.1875
  lightness: 0.7893617
  saturation: 0.3125
  rhythmicContrast: 0.75
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.516
analytics:
  google: null
  facebook: null
  twitter: null
name: LADY KIWI
cta:
  domain: null
  bucket: null
  version: null
favicon: null
collections:
  - index:
      paginate: true
      path: /
      number: 15
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      format: rss
      path: /rss.xml
      number: 10
title: Lady Kiwi
purpose: []
