name: LADY KIWI
favicon: null
layout_spectrum: 1
typography_spectrum: 0.35347
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#b8d4ae'
    - '#73ab62'
    - '#00100d'
    - '#2a4124'
  brandStrength: 1
  lightness: 1
  saturation: 1
  rhythmicContrast: 1
purpose: []
