name: LADY KIWI
favicon: null
layout_spectrum: 0.6690130783244967
typography_spectrum: 0.4349406457040459
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.0895794341340661
  lightness: 0.05039323284290731
  saturation: 0.45756935328245163
  rhythmicContrast: 0.9163537812419236
purpose: []
