name: LADY KIWI
favicon: null
layout_spectrum: 0.24752
typography_spectrum: 0.4042553
collections:
  - index:
      paginate: true
      path: /
      number: 15
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      format: rss
      path: /rss.xml
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f7f4ed'
    - '#e28f63'
    - '#c9784d'
    - '#e7c095'
    - '#a85935'
  brandStrength: 0.3125
  lightness: 0.7893617
  saturation: 0.3125
  rhythmicContrast: 0.75
purpose: []
