analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 1
  brandStrength: 1
  lightness: 0.3851064
  brandColors:
    - '#ffffff'
    - '#b8d4ae'
    - '#73ab62'
    - '#00100d'
    - '#2a4124'
  rhythmicContrast: 0
typography_spectrum: 0.4042553
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 1
favicon: null
name: LADY KIWI
